Options:
  Strength-color: '54c6e93b2a' #强度颜色
  Time: 100
  HistoryForge: true #为true则启用历史锻造 为false则不启用  会直接打开锻造列表
Continued: false #为true则是一直增加强度  要么扣完  要么就是没物品了  false就是只扣一次  当个保底
Item: #强度石？好像是叫这玩意
  '低级强度石': #这里你爱填啥填啥
    Lore: '&a增加基础强度' #唉，我就是不判断物品，只判断lore！就是玩儿！
    Add: 1  #这里嘛  就代表石头能增加的强度  当然  溢出会转换成满强度
  '满级强度石': #这里你爱填啥填啥
    Lore: '&a强度直接拉满' #唉，我就是不判断物品，只判断lore！就是玩儿！
    Add: 10  #这里嘛  就代表石头能增加的强度  当然  溢出会转换成满强度